# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "ecosystem"
    url = "/packages/"
    weight = 1
    
[[main]]
    name = "getting started"
    url = "/getting_started/"
    weight = 2

[[main]]
    name = "using torch"
    url = "/using_torch/"
    weight = 3
    
[[main]]
    name = "getting technical"
    url = "/technical/"
    weight = 4
    
[[main]]
    name = "docs"
    url = "/docs/"
    weight = 5

[[main]]
    name = "blog"
    url = "https://blogs.rstudio.com/ai/"
    weight = 6


