# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "ecosystem"
    url = "/packages/"
    weight = 1
    
[[main]]
    name = "get started"
    url = "/start/"
    weight = 2
    
[[main]]
    name = "use torch"
    url = "/using_torch/"
    weight = 3
    
[[main]]
    name = "get technical"
    url = "/technical/"
    weight = 4
    
[[main]]
    name = "resources"
    url = "/resources/"
    weight = 5

[[main]]
    name = "docs"
    url = "/docs/"
    weight = 6
    


